src/basic/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    public function actionExpedientes()
    {
        return $this->render('expedientes');
    }
}

src/basic/views/layouts/BAK_main.php
<?php
use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode(Yii::$app->name) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar navbar-expand-md navbar-dark bg-dark ',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar navbar-nav w-100 justify-content-end'],
        'items' =>[
        [   
            'label' => '<i class="fas fa-book"></i> Expedientes', 
            'url' => ['/expediente'],
        ],
        [
            'label' => '<i class="fas fa-clipboard-list"></i> Tipos de Expedientes', 
            'url' => ['/tipoexpediente'],
        ],
        [
            'label' => '<i class="far fa-object-group"></i> Areas',
            'url' => ['/area']
        ],
        [   
            'label' => '<i class="fas fa-users"></i> Usuarios', 
            'url' => ['/user'],
        ],
            
            Yii::$app->user->isGuest ? (
                [
                    'label' => 'Login',
                    'url' => ['/site/login'],
                ]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
        'encodeLabels' => false,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer pull-botton">
    <div class="container">
        <p class="pull-left">&copy; Promocion Curza <?= date('Y') ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>
<style type="text/css">
.wrap > .container {
    padding: 0px 15px 20px;
}
</style>

src/basic/views/layouts/bootstrap4 copy.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap4\NavBar;
use yii\bootstrap4\Nav;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;


?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Expedientes',
        'brandUrl' => '/expediente',
        'options' => [
            'class' => 'navbar navbar-expand-md navbar-dark bg-dark ',
        ],
    ]);
    echo Nav::widget([
        'options' => [
            'class' => 'navbar navbar-nav w-100 justify-content-end',
        ],
        'items' => [
            ['label' => 'Expedientes', 'url' => ['/expediente']],
            Yii::$app->user->isGuest ? (
            ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>
    <div class="container">
        <?= $content ?>
    </div>
</div>
<footer class="card-footer">
    <div class="container">
        <p class="pull-left">&copy; Promocion Curza <?= date('Y') ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

src/basic/views/layouts/main.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use app\assets\VueAsset;
use app\widgets\Alert;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

$this->registerCssFile("//unpkg.com/bootstrap/dist/css/bootstrap.min.css",['position'=>$this::POS_HEAD]);
$this->registerCssFile("//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.min.css",['position'=>$this::POS_HEAD]);
//$this->registerCssFile("https://unpkg.com/font-awesome@4.7.0/css/font-awesome.css",['position'=>$this::POS_HEAD]);
$this->registerCssFile("https://use.fontawesome.com/releases/v5.0.13/css/all.css",['position'=>$this::POS_HEAD]);


$this->registerJsFile("https://unpkg.com/sweetalert2@7.26.29/dist/sweetalert2.all.min.js",['position'=>$this::POS_HEAD]);
$this->registerJsFile("https://cdn.jsdelivr.net/npm/vue/dist/vue.js",['position'=>$this::POS_HEAD]);
$this->registerJsFile("https://unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.min.js",['position'=>$this::POS_HEAD]);
$this->registerJsFile("https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js",['position'=>$this::POS_HEAD]);
$this->registerJsFile("https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js",['position'=>$this::POS_HEAD]);


//Redireccionar al Login cuando no existe un token
$this->registerJs('
    //Verifica que exista el token almacenado
    if (!localStorage.access_token && window.location.pathname !== "/login") {
        window.location.href = "/login";
    } else {
        //Si no hubo redirección muestra el contenido y el nombre de usuario
        document.body.style.display="block";
        appUsername = document.getElementById("logout");
        appUsername.textContent = " " + localStorage.username + " (Salir)";
    }
');

$this->registerJs('   
    //Eliminar datos de sesion 
    function logout() {
        localStorage.clear();
        window.location.href = "/login";
    }
', \yii\web\View::POS_HEAD);

//Registrar CSS y JS para Vue y Bootstrap 4
VueAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">

    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php $this->registerCsrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>

    <body style="display: none;">
        <?php $this->beginBody() ?>
        <div class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="navbar navbar-nav w-100 justify-content-end" id="navbar" style="display: <?= (Yii::$app->request->url != '/login') ? 'block' : 'none' ?>">
            <div class="container" >
                <?= Html::a(' Inicio', ['/'], ['class' => 'fas fa-home text-white']) ?>
                <?= Html::a(' Expediente', ['/expediente'], ['class' => 'fas fa-book text-white']) ?>
                <?= Html::a(' Tipoexpediente', ['/tipoexpediente'], ['class' => 'fas fa-clipboard-list text-white']) ?>
                <?= Html::a(' Area', ['/area'], ['class' => 'fas fa-object-group text-white']) ?>
                <?= Html::a(' Usuarios', ['/user'], ['class' => 'fas fa-user text-white']) ?>
                <?= Html::a('', ['#'], ['id' => 'logout','class'=>'fas fa-power-off text-white', 'onclick' => 'logout()']) ?>

            </div>
        </div>
        </div>

        <div class="wrap">
            <div class="">
                <?= $content ?>
            </div>
        </div>

        <?php $this->beginBody() ?>

        <?php $this->endBody() ?>
    </body>

</html>
<?php $this->endPage() ?>

src/basic/views/layouts/main_old.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar navbar-expand-md navbar-dark bg-dark ',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar navbar-nav w-100 justify-content-end'],
        'items' => [
            ['label' => 'areas', 'url' => ['/site/areas']],
            ['label' => 'expedientes', 'url' => ['/site/expedientes']],
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer pull-botton">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>